include!("../include/bindings.rs");

const GPIO_LD1: u32 = GPIO_OUTPUT | GPIO_PUSHPULL | GPIO_SPEED_50MHz | GPIO_OUTPUT_CLEAR | GPIO_PORTB | GPIO_PIN0;
const GPIO_LD2: u32 = GPIO_OUTPUT | GPIO_PUSHPULL | GPIO_SPEED_50MHz | GPIO_OUTPUT_CLEAR | GPIO_PORTB | GPIO_PIN7;
const GPIO_LD3: u32 = GPIO_OUTPUT | GPIO_PUSHPULL | GPIO_SPEED_50MHz | GPIO_OUTPUT_CLEAR | GPIO_PORTB | GPIO_PIN14;

const GPIO_LED_GREEN: u32 = GPIO_LD1;
const GPIO_LED_BLUE: u32 = GPIO_LD2;
const GPIO_LED_RED: u32 = GPIO_LD3;
