[package]
name = "large-board"
version = "0.1.0"
edition = "2021"

build = "build.rs"

# Configuration for Static Library Building
[lib]
name = "nucleo_rs"
path = "src/lib.rs"
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# Dependencies for our project
[dependencies]
cty = "0.2.2"
cfg-if = "1.0"  # used throughout as a conditional dependencies
log = "0.4.21"  # used to replicate warnings and errors at compile time

# Build Dependencies for our project
[build-dependencies]
bindgen = "0.69.4"
