[package]
name = "crust"
version = "0.1.0"
edition = "2021"

# Configuration for Static Library Building
[lib]
name = "resetRust"
path = "src/stm32_reset.rs"
crate-type = ["staticlib"]

# [build]
# out-dir = "./"
# target-dir = "./"

# Build Dependancies for our project
[dependencies]
