[package]
name = "large-board"
version = "0.1.0"
edition = "2021"

build = "build.rs"

# Configuration for Static Library Building
[lib]
name = "nucleo_rs"
path = "src/lib.rs"
crate-type = ["staticlib"]


# Dependencies for our project
[dependencies]
cty = "0.2.2"

# Build Dependencies for our project
[build-dependencies]
bindgen = "0.69.4"
