[package]
name = "large-board"
version = "0.1.0"
edition = "2021"

build = "build.rs"

# Configuration for Static Library Building
[lib]
name = "nucleo_rs"
path = "src/lib.rs"
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# Dependencies for our project
[dependencies]
cty = "0.2.2"
cfg-if = "1.0"  # used throughout as a conditional dependencies
libc = "0.2.139"

heapless = "*"

log = "0.4.21"  # used to replicate warnings and errors at compile time
thiserror-no-std = "2.0.2" # no std version of throwing errors

# Build Dependencies for our project
[build-dependencies]
bindgen = "0.69.4"

[features]
default = []
# used in usb
CONFIG_STM32F7_OTGFS = []
CONFIG_USBDEV = []
CONFIG_USBHOST = []
CONFIG_NUCLEO144_USBHOST_PRIO = []
CONFIG_NUCLEO_USBHOST_STACKSIZE = []
GPIO_OTGFS_VBUS = []
GPIO_OTGFS_PWRON = []
GPIO_OTGFS_OVER = []
CONFIG_USBHOST_HUB = []
CONFIG_USBHOST_MSC = []
CONFIG_USBHOST_CDCACM = []
CONFIG_USBHOST_HIDKBD = []
CONFIG_USBHOST_HIDMOUSE = []
# end of in usb
# used in spi
CONFIG_SPI = []
CONFIG_NUCLEO_SPI1_TEST = []
CONFIG_NUCLEO_SPI1_TEST_MODE0 = []
CONFIG_NUCLEO_SPI1_TEST_MODE1 = []
CONFIG_NUCLEO_SPI1_TEST_MODE2 = []
CONFIG_NUCLEO_SPI1_TEST_MODE3 = []
CONFIG_NUCLEO_SPI2_TEST = []
CONFIG_NUCLEO_SPI2_TEST_MODE0 = []
CONFIG_NUCLEO_SPI2_TEST_MODE1 = []
CONFIG_NUCLEO_SPI2_TEST_MODE2 = []
CONFIG_NUCLEO_SPI2_TEST_MODE3 = []
CONFIG_NUCLEO_SPI3_TEST = []
CONFIG_NUCLEO_SPI3_TEST_MODE0 = []
CONFIG_NUCLEO_SPI3_TEST_MODE1 = []
CONFIG_NUCLEO_SPI3_TEST_MODE2 = []
CONFIG_NUCLEO_SPI3_TEST_MODE3 = []
CONFIG_STM32F7_SPI1 = []
GPIO_SPI1_CS0 = []
GPIO_SPI1_CS1 = []
GPIO_SPI1_CS2 = []
GPIO_SPI1_CS3 = []
CONFIG_STM32F7_SPI2 = []
GPIO_SPI2_CS0 = []
GPIO_SPI2_CS1 = []
GPIO_SPI2_CS2 = []
GPIO_SPI2_CS3 = []
CONFIG_STM32F7_SPI3 = []
GPIO_SPI3_CS0 = []
GPIO_SPI3_CS1 = []
GPIO_SPI3_CS2 = []
GPIO_SPI3_CS3 = []
CONFIG_NUCLEO_SPI_TEST = []
CONFIG_STM32F7_SPI1 = []
CONFIG_STM32F7_SPI2 = []
CONFIG_STM32F7_SPI3 = []
CONFIG_STM32F7_SPI4 = []
CONFIG_STM32F7_SPI5 = []
CONFIG_STM32F7_SPI6 = []
CONFIG_SPI_CMDDATA = []
CONFIG_NUCLEO_SPI_TEST_MESSAGE = []
CONFIG_NUCLEO_SPI1_TEST_FREQ = []
CONFIG_NUCLEO_SPI1_TEST_BITS = []
CONFIG_NUCLEO_SPI1_TEST_MODE = []
CONFIG_NUCLEO_SPI_TEST_MESSAGE = []
CONFIG_NUCLEO_SPI2_TEST_FREQ = []
CONFIG_NUCLEO_SPI2_TEST_BITS = []
CONFIG_NUCLEO_SPI2_TEST_MODE = []
CONFIG_NUCLEO_SPI_TEST_MESSAGE = []
CONFIG_NUCLEO_SPI3_TEST_FREQ = []
CONFIG_NUCLEO_SPI3_TEST_BITS = []
CONFIG_NUCLEO_SPI3_TEST_MODE = []
CONFIG_NUCLEO_SPI_TEST_MESSAGE = []
# end of in spi