[package]
name = "large-board"
version = "0.1.0"
edition = "2021"

# Configuration for Static Library Building
[lib]
name = "nucleo_rs"
path = "src/stm32_autoleds.rs"
crate-type = ["staticlib"]


# Build Dependancies for our project
[dependencies]
